fastlane_version "2.66.0"

default_platform :ios

lane :bump do
  ensure_git_status_clean
  increment_build_number
  commit_version_bump
end

platform :ios do
  
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    bump
    gym
    pilot(changelog: options[:changelog], distribute_external: true, groups: ['External Testers'])
    push_to_git_remote
  end
end

platform :mac do
  lane :archive do
    gym(scheme: 'imastodon-mac',
        clean: true,
        codesigning_identity: 'Developer ID Application')
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
